skip_tags: true
only_commits:
  files:
    - appveyor.yml
    - sp/src/**

image:
  - Visual Studio 2013

clone_depth: 1

install:
  - |-
    cd sp\src
    devtools\bin\vpc.exe /hl2 +game /mksln games.sln
    "%PROGRAMFILES(X86)%\Microsoft Visual Studio 12.0\Common7\IDE\devenv.com" games.sln /upgrade
    cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - msbuild sp\src\games.sln /p:Configuration=Release;Platform=Win32 /m /v:m /logger:"%PROGRAMFILES%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - 7z a hl2-pdb.zip .\sp\src\game\server\.\Release_mod_hl2\server.dll .\sp\src\game\server\.\Release_mod_hl2\server.pdb .\sp\src\game\client\.\Release_mod_hl2\client.dll .\sp\src\game\client\.\Release_mod_hl2\client.pdb

test: off

artifacts:
  - path: hl2-pdb.zip
